### ISSUE TITLE
where is the cloudfront.yml file?

### ISSUE THREAD

**Issue by melvin-omh** [aws-samples/amazon-cloudfront-continuousdeployment-cicd#1]
Hi @jasonbrd , 
Thank you for this sample CI/CD for Cloudfront distribution, this is exactly what I need right now.
I have a question, under `Deploying the solution:` Step No. 3, it was mentioned that I need to make changes to the cloudfront.yml file, I can't see it in the repo though, what is the content of this file?

**Comment by jasonbrd** [comment]
@melvin-omh Thanks for bringing this to our attention. The original step 3 was a mistaken duplicate entry in the README instructions. Step 4 was the actual next step. The readme has been updated and merged for correction. Thanks for the feedback and we hope this solution is helpful for you!
